// Promotions (static data) for GitHub Pages.
// Later this can be replaced by API / CMS.
window.REMCARD_PROMOTIONS = [
  {
    id: 1,
    title: "Бесплатный выезд и замер по Краснодару",
    partnerName: "ООО “КрасСтройРемонт”",
    city: "Краснодар",
    category: "Ремонт под ключ",
    description: "Выезд специалиста и замер бесплатно при оформлении заявки через RemCard.",
    discount: "Бесплатный выезд",
    validUntil: "2026-03-15",
    tags: ["Для квартиры", "Замер", "Под ключ"],
    link: "#request",
    isFeatured: true,
  },
  {
    id: 2,
    title: "Скидка −15% на ремонт ванной/санузла",
    partnerName: "Иван Петров",
    city: "Краснодар",
    category: "Ремонт ванной",
    description: "Скидка на работы по ремонту санузла при заявке через RemCard. Материалы — по согласованию.",
    discount: "−15%",
    validUntil: "2026-02-28",
    tags: ["Санузел", "Плитка", "Сантехника"],
    link: "#request",
    isFeatured: true,
  },
  {
    id: 3,
    title: "Дизайн‑консультация 60 минут бесплатно",
    partnerName: "Мария Смирнова",
    city: "Краснодар",
    category: "Дизайн",
    description: "Первичная консультация по планировке и стилю. Подойдёт перед началом ремонта.",
    discount: "0 ₽ консультация",
    validUntil: "2026-03-05",
    tags: ["Дизайн", "Планировка", "Для квартиры"],
    link: "#request",
    isFeatured: false,
  },
  {
    id: 4,
    title: "Скидка 10 000 ₽ на ремонт под ключ",
    partnerName: "ООО “КрасСтройРемонт”",
    city: "Краснодар",
    category: "Ремонт под ключ",
    description: "Фиксированная скидка при объёме работ от 40 м². Условия уточняйте в заявке.",
    discount: "−10 000 ₽",
    validUntil: "2026-04-01",
    tags: ["Под ключ", "Новостройка", "Смета"],
    link: "#request",
    isFeatured: true,
  },
  {
    id: 5,
    title: "Доставка сантехники по Краснодару — бесплатно",
    partnerName: "“СантехМаркет Юг”",
    city: "Краснодар",
    category: "Сантехника",
    description: "Бесплатная доставка по Краснодару при заказе от 15 000 ₽. Поможем с подбором комплектации.",
    discount: "Бесплатная доставка",
    validUntil: null,
    tags: ["Сантехника", "Доставка", "Для дома"],
    link: "#request",
    isFeatured: true,
  },
  {
    id: 6,
    title: "Смета за 24 часа (проверка и рекомендации)",
    partnerName: "RemCard",
    city: "Краснодар",
    category: "Консультация",
    description: "Пришлите смету — подскажем, где можно оптимизировать и на что обратить внимание.",
    discount: "Бесплатно",
    validUntil: "2026-03-31",
    tags: ["Смета", "Экономия", "Консультация"],
    link: "#request",
    isFeatured: false,
  },
];
