// Promotions (static data) for GitHub Pages.
// Type shape (for future API parity):
// id, title, partnerName, city, description,
// benefitType: PERCENT | AMOUNT | FREE | OTHER,
// benefitValue, benefitLabel, categoryTags, validUntil, bannerImageUrl, createdAt
window.REMCARD_PROMOTIONS = [
  {
    id: 1,
    title: "Бесплатный выезд и замер по Краснодару",
    partnerName: "ООО “КрасСтройРемонт”",
    city: "Краснодар",
    description: "Выезд специалиста и замер бесплатно при оформлении заявки через RemCard.",
    benefitType: "FREE",
    benefitValue: null,
    benefitLabel: "Бесплатно",
    categoryTags: ["Ремонт под ключ", "Замер", "Для квартиры"],
    validUntil: "2026-03-15",
    bannerImageUrl: null,
    createdAt: "2026-02-14",
    link: "#request",
    isFeatured: true
  },
  {
    id: 2,
    title: "Скидка −15% на ремонт ванной/санузла",
    partnerName: "Иван Петров",
    city: "Краснодар",
    description: "Скидка на работы по ремонту санузла при заявке через RemCard. Материалы — по согласованию.",
    benefitType: "PERCENT",
    benefitValue: 15,
    benefitLabel: "−15%",
    categoryTags: ["Санузел", "Плитка", "Сантехника"],
    validUntil: "2026-03-28",
    bannerImageUrl: null,
    createdAt: "2026-02-20",
    link: "#request",
    isFeatured: true
  },
  {
    id: 3,
    title: "Дизайн‑консультация 60 минут бесплатно",
    partnerName: "Мария Смирнова",
    city: "Краснодар",
    description: "Первичная консультация по планировке и стилю. Подойдёт перед началом ремонта.",
    benefitType: "FREE",
    benefitValue: null,
    benefitLabel: "Бесплатно",
    categoryTags: ["Дизайн", "Планировка", "Консультация"],
    validUntil: "2026-04-05",
    bannerImageUrl: null,
    createdAt: "2026-03-01",
    link: "#request",
    isFeatured: false
  },
  {
    id: 4,
    title: "Скидка 10 000 ₽ на ремонт под ключ",
    partnerName: "ООО “КрасСтройРемонт”",
    city: "Краснодар",
    description: "Фиксированная скидка при объёме работ от 40 м². Условия уточняйте в заявке.",
    benefitType: "AMOUNT",
    benefitValue: 10000,
    benefitLabel: "−10 000 ₽",
    categoryTags: ["Ремонт под ключ", "Новостройка", "Смета"],
    validUntil: "2026-04-01",
    bannerImageUrl: null,
    createdAt: "2026-03-03",
    link: "#request",
    isFeatured: true
  },
  {
    id: 5,
    title: "Доставка сантехники по Краснодару — бесплатно",
    partnerName: "“СантехМаркет Юг”",
    city: "Краснодар",
    description: "Бесплатная доставка по Краснодару при заказе от 15 000 ₽. Поможем с подбором комплектации.",
    benefitType: "FREE",
    benefitValue: null,
    benefitLabel: "Бесплатная доставка",
    categoryTags: ["Сантехника", "Доставка", "Для дома"],
    validUntil: null,
    bannerImageUrl: null,
    createdAt: "2026-03-04",
    link: "#request",
    isFeatured: true
  },
  {
    id: 6,
    title: "Смета за 24 часа (проверка и рекомендации)",
    partnerName: "RemCard",
    city: "Краснодар",
    description: "Пришлите смету — подскажем, где можно оптимизировать и на что обратить внимание.",
    benefitType: "OTHER",
    benefitValue: 1,
    benefitLabel: "Проверка сметы",
    categoryTags: ["Смета", "Экономия", "Консультация"],
    validUntil: "2026-03-31",
    bannerImageUrl: null,
    createdAt: "2026-03-05",
    link: "#request",
    isFeatured: false
  }
];
